upstream obsidian_relay {
    server 172.16.0.1:3200;
    keepalive 64;
}

upstream obsidian_minio {
    server 172.16.0.1:3202;
    keepalive 8;
}

server {
    listen 8880;
    server_name obsidian.wgwg.ru;
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 4443 ssl;
    server_name obsidian.wgwg.ru;

    ssl_certificate     /etc/letsencrypt/live/obsidian.wgwg.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/obsidian.wgwg.ru/privkey.pem;
    include /etc/nginx/snippets/ssl-params.conf;

    location /relay/ {
        proxy_pass http://obsidian_minio/relay/;
        proxy_set_header Host minio:9000;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
        proxy_request_buffering off;
    }

    location /f/ {
        proxy_pass http://obsidian_relay;
        include /etc/nginx/snippets/proxy-params.conf;

        proxy_http_version 1.1;
        proxy_read_timeout  300s;
        proxy_send_timeout  300s;
        proxy_buffering     on;

        sub_filter "http://minio:9000" "https://obsidian.wgwg.ru";
        sub_filter_once off;
        sub_filter_types application/json text/plain;
    }

    location ~ ^/([^/]+)$ {
        proxy_pass http://obsidian_relay/d/$1/ws/$1;
        include /etc/nginx/snippets/proxy-params.conf;

        proxy_http_version 1.1;
        proxy_set_header Upgrade    $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_read_timeout  86400s;
        proxy_send_timeout  86400s;
        proxy_buffering     off;
    }

    location / {
        proxy_pass http://obsidian_relay;
        include /etc/nginx/snippets/proxy-params.conf;

        proxy_http_version 1.1;
        proxy_set_header Upgrade    $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_read_timeout  86400s;
        proxy_send_timeout  86400s;
        proxy_buffering     off;
    }
}
