import esbuild from "esbuild";
import process from "process";
import esbuildSvelte from "esbuild-svelte";
import sveltePreprocess from "svelte-preprocess";
import builtins from "builtin-modules";
import { execSync } from "child_process";
import chokidar from "chokidar";
import path from "path";
import fs, { mkdirSync } from "fs";
import { createRequire } from "module";

const workspaceRoot = path.resolve(import.meta.dirname, "../..");
const require = createRequire(import.meta.url);
const packageVersion = JSON.parse(fs.readFileSync("package.json", "utf8")).version;
const localYjsInternalsPath = path.join(import.meta.dirname, "node_modules", "yjs", "src", "internals.js");
const workspaceYjsInternalsPath = path.join(workspaceRoot, "node_modules", "yjs", "src", "internals.js");
const yjsInternalsPath = fs.existsSync(localYjsInternalsPath)
	? localYjsInternalsPath
	: fs.existsSync(workspaceYjsInternalsPath)
		? workspaceYjsInternalsPath
		: require.resolve("yjs/src/internals.js");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const gitTag = execSync("git describe --tags --always", {
	encoding: "utf8",
}).trim();
const releaseVersion = packageVersion || gitTag;

const develop = process.argv[2] === "develop";
const staging = process.argv[2] === "staging";
const watch = process.argv[2] === "watch" || staging;
const debug = process.argv[2] === "debug" || watch || staging || develop;
const out = process.argv[3] || ".";
const tld = staging ? "dev" : "md";

// Obsidian vault plugin directory for auto-copy on build
const obsidianPluginDir = process.env.OBSIDIAN_PLUGIN_DIR ||
	path.join(process.env.HOME, "Obsidian/Rogozhin/.obsidian/plugins/evc-team-relay");

// EVC Team Relay uses relay-onprem mode, no default System 3 URLs
const apiUrl = "";
const authUrl = "";
const healthUrl = apiUrl ? `${apiUrl}/health?version=${releaseVersion}` : "";
console.log("git tag:", gitTag);
console.log("package version:", releaseVersion);
if (healthUrl) {
	console.log("health URL", healthUrl);
}

const NotifyPlugin = {
	name: "on-end",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0 && process.platform !== "win32" && !process.env.CI) {
				try {
					execSync(`command -v notify-send >/dev/null 2>&1 && notify-send "Build Failed"`);
				} catch {
					// Best-effort desktop notification only.
				}
			}
		});
	},
};

const YjsInternalsPlugin = {
	name: "yjs-internals",
	setup(build) {
		build.onResolve({ filter: /^yjs\/dist\/src\/internals$/ }, args => {
			return {
				path: yjsInternalsPath,
			};
		});
	},
};

// Ensure all `yjs` imports resolve to the same copy.
const yjsMainPath = require.resolve("yjs");
const YjsDedupePlugin = {
	name: "yjs-dedupe",
	setup(build) {
		build.onResolve({ filter: /^yjs$/ }, () => {
			return { path: yjsMainPath };
		});
	},
};

// Strip Yjs duplicate-import check from the bundle.
// Obsidian's runtime loads its own Yjs copy; our bundled copy triggers
// a false-positive warning. We remove the check at load time.
const YjsStripDuplicateCheckPlugin = {
	name: "yjs-strip-duplicate-check",
	setup(build) {
		build.onLoad({ filter: /yjs[/\\]dist[/\\]yjs\.cjs$/ }, async (args) => {
			let contents = fs.readFileSync(args.path, "utf8");
			// Replace the duplicate check block with a no-op
			contents = contents.replace(
				/if\s*\(glo\[importIdentifier\]\s*===\s*true\)\s*\{[\s\S]*?console\.error\([^)]*\);\s*\}\s*\nglo\[importIdentifier\]\s*=\s*true;/,
				"// Yjs duplicate check removed by esbuild plugin"
			);
			return { contents, loader: "js" };
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
        "moment",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	plugins: [
		esbuildSvelte({
			compilerOptions: { css: true },
			preprocess: sveltePreprocess(),
		}),
		YjsDedupePlugin,
		YjsStripDuplicateCheckPlugin,
		YjsInternalsPlugin,
		NotifyPlugin,
	],
	target: "es2018",
	minify: !debug,
	logLevel: "info",
	sourcemap: debug ? "inline" : false,
	define: {
		BUILD_TYPE: debug ? '"debug"' : '"prod"',
		GIT_TAG: `"${releaseVersion}"`,
		HEALTH_URL: `"${healthUrl}"`,
		API_URL: `"${apiUrl}"`,
		AUTH_URL: `"${authUrl}"`,
		REPOSITORY: `"WoodGear1/evc-team-relay-selfhosted"`,
	},
	treeShaking: true,
	loader: {
		".png": "dataurl",
	},
	outfile: out + "/main.js",
});

const copyFile = (src, dest) => {
	if (src === dest) {
		return;
	}
	fs.copyFileSync(src, dest);
	console.log(`Copied ${src} to ${dest}`);
};

const watchAndMove = (fnames, mapping) => {
	// only usable on top level directory
	const watcher = chokidar.watch(fnames, {
		ignored: /(^|[\/\\])\../, // ignore dotfiles
		persistent: true,
	});

	watcher.on("change", (filePath) => {
		const destName = mapping[filePath] || filePath;
		const destPath = path.join(out, path.basename(destName));
		copyFile(filePath, destPath);
	});
};

const mapping = debug ? { "manifest-beta.json": "manifest.json" } : {};
const manifest = debug ? "manifest-beta.json" : "manifest.json";
const files = ["styles.css", manifest];

const updateManifest = (manifest) => {
	const manifestPath = path.join(out, path.basename("manifest.json"));
	const raw_manifest = fs.readFileSync(manifestPath);
	const parsed = JSON.parse(raw_manifest);
	parsed.version = releaseVersion;
	const new_manifest = JSON.stringify(parsed, null, 2);
	console.log(`Set ${manifest} version to ${releaseVersion}`);
	fs.writeFileSync(manifestPath, new_manifest);
};

const move = (fnames, mapping) => {
	// only usable on top level directory
	mkdirSync(out, { recursive: true });
	for (const fname of fnames) {
		const destName = mapping[fname] || fname;
		const destPath = path.join(out, path.basename(destName));
		copyFile(fname, destPath);
	}
};

// Copy build output to Obsidian plugin directory
const copyToObsidian = () => {
	if (!fs.existsSync(obsidianPluginDir)) {
		console.log(`Obsidian plugin dir not found: ${obsidianPluginDir}`);
		return;
	}
	const filesToCopy = ["main.js", "manifest.json", "styles.css"];
	for (const fname of filesToCopy) {
		const src = path.join(out, fname);
		const dest = path.join(obsidianPluginDir, fname);
		if (fs.existsSync(src)) {
			copyFile(src, dest);
		}
	}
	console.log(`Copied to Obsidian: ${obsidianPluginDir}`);
};

if (watch) {
	await context.watch();
	move(files, mapping);
	if (!develop) {
		updateManifest();
	}
	copyToObsidian();
	watchAndMove(files, mapping);
} else {
	await context.rebuild();
	move(files, mapping);
	if (!develop) {
		updateManifest();
	}
	copyToObsidian();
	process.exit(0);
}
